version: "3.3"
services:
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: heal-n-go-be
    container_name: heal-n-go-be
    restart: unless-stopped
    env_file: .env
    ports:
      # host:docker
      - "5000:5000"
